# Performing Matrix Operations Using Pytorch Functions

### We will perform different types of matrix operations using pytorch functions. 

PyTorch is an open source machine learning library. Tensors are classes in Pytorch used to store and perform different types of operations on multidimensional arrays. We have chosen 5 tensor functions and see how these functions ca be used to peform respective matrix operation.
- torch.matmul()
- torch.transpose()
- torch.inverse()
- torch.trace()
- torch.eig()

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.matmul() 

Helps to multiply two matrices. 
The syntax of the funtion is:  torch.matmul(input, other, out=None)

In [2]:
# Example 1 - working 
a=torch.tensor([[1,2,3], [4,5,6],[7,8,9]])
b=torch.tensor([[10,11,12], [13,14,15],[16,17,18]])
c=torch.matmul(a,b)
print ("A=",a)
print("B=",b)
print ("Matrix Multiplication of A & B:",c)

A= tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
B= tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
Matrix Multiplication of A & B: tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])


We have taken two matices 'a' and 'b', and matrix 'c' computes the product of matrix 'a' & 'b'.

In [14]:
# Example 2 - working
e=torch.rand(3,2)
print(e)
f=torch.rand(2,3)
print(f)
g=torch.matmul(e,f)
print(g)

tensor([[0.3649, 0.1195],
        [0.7247, 0.8259],
        [0.1519, 0.8076]])
tensor([[0.0532, 0.5970, 0.8126],
        [0.2806, 0.0418, 0.7313]])
tensor([[0.0529, 0.2229, 0.3840],
        [0.2703, 0.4672, 1.1928],
        [0.2347, 0.1245, 0.7140]])


Here we took two random matrices and evaluated the product of the two matrices. To fill the matrix with random numbers we use the function torch.rand(rows,columns). e is matrix of size 3x2 ,and f is of size 2x3 and hence we get the product as a 3x3 matrix.

In [16]:
# Example 3 - breaking 
e=torch.rand(3,2)
print(e)
f=torch.rand(3,3)
print(f)
g=torch.matmul(e,f)
print(g)


tensor([[0.0041, 0.8590],
        [0.6120, 0.3612],
        [0.5991, 0.0395]])
tensor([[0.8569, 0.1524, 0.3959],
        [0.0745, 0.5204, 0.3161],
        [0.6167, 0.7603, 0.5709]])


RuntimeError: size mismatch, m1: [3 x 2], m2: [3 x 3] at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensorMath.cpp:41

Here we took a tried to multiply two random matrices, but as we know the rule of matrix multiplication is no. of columns of the 1st matrix= no of rows of the 2nd matrix. This rule is not being follwed here that's why we are getting an error.

So, We can conclude that whenwever we need to evaluate the matrix multiplication of two marices we should use the torch.matmul() function and we should follow the rule of matrix multiplication, i.e no. of columns of the 1st matrix= no of rows of the 2nd matrix.

## Function 2 - torch.transpose()

torch.transpose() is used to find the transpose of a matrix. Transpose of a matrix flips the matrix over its diagonal, i.e the values of the matrix of ij are swapped with ji. The syntax is : torch.transpose(input, dim0, dim1) ,dimension 0 is swapped with dimension 1 

In [18]:
# Example 1 - working
a=torch.rand(3,2)
print(a)
b=torch.transpose(a,0,1)
print(b)

tensor([[0.1893, 0.9065],
        [0.5363, 0.4449],
        [0.1657, 0.6104]])
tensor([[0.1893, 0.5363, 0.1657],
        [0.9065, 0.4449, 0.6104]])


As we can see the rows and columns are swapped, ij is swapped with ji.

In [19]:
# Example 2 - working
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=torch.transpose(a,0,1)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


Here we took a matrix 'a' and computed its transpose.

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.rand(3,2)
b=torch.transpose(a)
print(b)

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, name dim0, name dim1)
 * (Tensor input, int dim0, int dim1)


As we can see a syntax error is present, because we are not specifying what to swap, we need to specify the dimension that needs to be swapped.

So, We can compute the transpose of a matrix using the torch.transpose() function but we need to mention the dimensions also, otherwise it will show an error.

## Function 3 - torch.inverse()

torch.inverse() is used to compute the inverse of a matrix. This is a very useful function as we often need to evaluate the inverse of a matrix. Finding the inverse of a matrix involves multiple steps but with the help of torch.inverse() function we can evaluate the inverse of a matrix in a single step. Syntax: torch.inverse(input, out=None)

In [21]:
# Example 1 - working
a=torch.rand(3,3)
print(a)
b=torch.inverse(a)
print(b)

tensor([[0.9730, 0.6992, 0.2283],
        [0.8901, 0.3237, 0.8778],
        [0.1244, 0.9746, 0.9667]])
tensor([[ 0.6278,  0.5245, -0.6246],
        [ 0.8691, -1.0552,  0.7530],
        [-0.9570,  0.9964,  0.3557]])


Here we have taken a random matrix 'a' of size 3x3 and evaluated its inverse using the torch.inverse() function.

In [22]:
# Example 2 - working
a=torch.tensor([[1.,2,3],[4,5,6],[7,8,9]])
print(a)
b=torch.inverse(a)
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[ -2796203.0000,   5592406.0000,  -2796203.0000],
        [  5592404.5000, -11184812.0000,   5592406.5000],
        [ -2796201.7500,   5592406.0000,  -2796203.2500]])


Here We have taken a matrix 'a' and evaluated its inverse.

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=torch.inverse(a)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


RuntimeError: "inverse_cpu" not implemented for 'Long'

Here we have taken the same matrix 'a' like above but this is showing an error.The only difference is that here matrix a is of integer type. So pytorch is assuming that the matrix 'b', i.e inverse of 'a' will also be an integer type matrix.That's why we are getting an error.

So, we have to always take into consideration that even if the values of input matrix are of integer type the output matrix (inverse of the input matrix) may be of floating type. Hence, we should always make sure that the input matrix is of floating type.(One simple way is to put a '.' after one of the value).
There are other rules of inverse that should also be taken into consideration, like the input matrix should be a square matrix, and it should not be a singular matrix(i.e det a=0). 

## Function 4 - torch.trace()

torch.trace() helps to evaluate the trace of a matrix. Trace of a matrix is the sum of its diagonal elements.

In [24]:
# Example 1 - working
a=torch.tensor([[1.,-1,2],[0,1,0],[1,2,1]])
print(a)
b=torch.trace(a)
print(b)

tensor([[ 1., -1.,  2.],
        [ 0.,  1.,  0.],
        [ 1.,  2.,  1.]])
tensor(3.)


We have taken a matrix 'a' and evaluated its trace. As we can see the sum of its diagonal element is 1+1+1 =3.

In [25]:
# Example 2 - working
a=torch.rand(3,3)
print(a)
b=torch.trace(a)
print(b)

tensor([[0.7848, 0.4059, 0.8074],
        [0.3442, 0.0891, 0.3804],
        [0.9950, 0.0484, 0.9380]])
tensor(1.8118)


Like the previous example we have computed the trace of a matrix. This time we have taken a random matrix of 3x3.

In [26]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.rand(3,3,3)
print(a)
b=torch.trace(a)
print(b)

tensor([[[0.9095, 0.3195, 0.2834],
         [0.4393, 0.5581, 0.7745],
         [0.0902, 0.0678, 0.6687]],

        [[0.3130, 0.6446, 0.6422],
         [0.4421, 0.6376, 0.3159],
         [0.1003, 0.3789, 0.4093]],

        [[0.7140, 0.8659, 0.2676],
         [0.5592, 0.0794, 0.6201],
         [0.9046, 0.0270, 0.2567]]])


RuntimeError: invalid argument 1: expected a matrix at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensorMoreMath.cpp:303

Here the matrix is 3-dimensional. trace of a 3D matrix cannot be found. So we need to give s 2D matrix to find the trace.

Thus, torch.trace() function can be used to find the sum of the diagonal of a given matrix.

## Function 5 - torch.eig()

torch.eig() is used to evaluate the eigen value and eigen vector of a matrix. Syntax: torch.eig(input, eigenvectors=False, out=None). Here input is the matrix for which we need to evaluate the eigen values.Eigenvectors is a boolean, if  it is set 'False', then the function only computes eigen value,if it's 'true' then it computes both eigen value and vector.

In [27]:
# Example 1 - working
a=torch.tensor([[1.,-1,2],[0,1,0],[1,2,1]])
print(a)
b=torch.eig(a,eigenvectors=True)
print(b)


tensor([[ 1., -1.,  2.],
        [ 0.,  1.,  0.],
        [ 1.,  2.,  1.]])
torch.return_types.eig(
eigenvalues=tensor([[ 2.4142,  0.0000],
        [-0.4142,  0.0000],
        [ 1.0000,  0.0000]]),
eigenvectors=tensor([[ 0.8165, -0.8165, -0.8729],
        [ 0.0000,  0.0000,  0.4364],
        [ 0.5774,  0.5774,  0.2182]]))


We have taken a matrix 'a' and computed the eigen values aand the eigen vector. The value of eigen vector is set to true.

In [28]:
# Example 2 - working
a=torch.rand(3,3)
print(a)
b=torch.eig(a)
print(b)

tensor([[0.9223, 0.4595, 0.4015],
        [0.2640, 0.9971, 0.5710],
        [0.9985, 0.2060, 0.7894]])
torch.return_types.eig(
eigenvalues=tensor([[ 1.8618,  0.0000],
        [ 0.4235,  0.1964],
        [ 0.4235, -0.1964]]),
eigenvectors=tensor([]))


Here, we have taken a random matrix of size 3x3 ,and we have not passed the eigenvectors parameter. By default it is set to False.

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.rand(3,2)
print(a)
b=torch.eig(a,eigenvectors=True)
print(b)

tensor([[0.9178, 0.0827],
        [0.4047, 0.4256],
        [0.5433, 0.4727]])


RuntimeError: invalid argument 1: A should be square at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensorLapack.cpp:194

The torch.eig() function needs square matrix, since eigen values cannot be computed for non-square matrices.

torch.eig() is an useful function.It helps us to find the eigen values and eigen vectors of a square matrix.

## Conclusion

We have seen the use of 5 pytorch functions in this note.We have used the matmul() function to multiply 2 matrices, then we have seen how to do traspose & inverse of a matrix, and lastly to find the trace and eigen values of a given matrix.We can use the above functions to do different types of matrix operations. There are many other functions present in the official pytorch documentation. 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Understanding dimensions in PyTorch:https://towardsdatascience.com/understanding-dimensions-in-pytorch-6edf9972d3be

In [3]:
!pip install jovian --upgrade --quiet

In [4]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
